apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: company-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: init-config-bundle-secret
  components:
    - kind: clair
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
    - kind: mirror
      managed: false    
